[project]
name = "LeakyBucketRateLimiter"
version = "0.1.0"
description = "Implementation of Rate Limiter(Leaky Bucket) based on Redis cache engine."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.9.10",
    "redis>=5.2.1",
]
